backend:
  name: git-gateway
  branch: master
media_folder: dentistfairfieldca.com/public/images
public_folder: /images
editor:
  preview: false
collections:
  - label: "Blog"
    name: "blog"
    folder: "dentistfairfieldca.com/src/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "date" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
